[package]
name = "backend"
version = "0.1.0"
edition = "2024"

[dependencies]
platforms = { workspace = true }
ort = { version = "2.0.0-rc.9", features = ["cuda", "load-dynamic"] }
opencv = "0.94.1"
anyhow = "1.0.95"
