[package]
name = "platforms"
version = "0.2.0"
edition = "2024"

[dependencies]
thiserror = "2"
bit-vec = "0.8"

[target.'cfg(windows)'.dependencies]
windows = { version = "0.59", features = [
    "Win32_UI_HiDpi",
    "Win32_Foundation",
    "Win32_UI_WindowsAndMessaging",
    "Win32_Graphics_Gdi",
    "Win32_UI_Input_KeyboardAndMouse",
] }

[target.'cfg(windows)'.build-dependencies]
tauri-winres = "0.1"

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "capture"
harness = false
