[package]
name = "platforms"
version.workspace = true
edition.workspace = true

[dependencies]
thiserror = "2"
bit-vec = "0.8"

[target.'cfg(windows)'.dependencies]
windows = { version = "0.59", features = [
    "Win32_UI_HiDpi",
    "Win32_Foundation",
    "Win32_UI_WindowsAndMessaging",
    "Win32_Graphics_Gdi",
    "Win32_UI_Input_KeyboardAndMouse",
] }

[target.'cfg(windows)'.build-dependencies]
tauri-winres = "0.1"
