[package]
name = "ui"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { workspace = true }
dioxus = { version = "0.6.3", features = ["desktop"] }
backend = { workspace = true }
serde = { workspace = true }
tracing-log = "0.2.0"
