[package]
name = "ui"
version = "0.1.0"
edition = "2024"

[dependencies]
dioxus = { version = "0.6.2", features = ["desktop"] }
backend = { workspace = true }
tokio = { version = "1.43.0" }
tracing-log = "0.2.0"
