[application]
name = "maple-bot"
asset_dir = "assets"

[web.app]
title = "Maple Bot"

[web.watcher]
watch_path = ["src", "assets"]

[web.resource]
style = ["public/tailwind.css"]
script = ["assets/autoNumeric.min.js"]

[web.resource.dev]
