name: Build windows-x64-static

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  VCPKG_DEFAULT_TRIPLET: x64-windows-static
  VCPKG_DEFAULT_HOST_TRIPLET: x64-windows-static
  VCPKG_ENABLE_METRICS: 0
  CARGO_TERM_COLOR: always
  OPENCV_MSVC_CRT: static

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install toolchain
        run: |
          rustup toolchain install nightly-x86_64-pc-windows-msvc --profile minimal
          rustup default nightly-x86_64-pc-windows-msvc

      - uses: Swatinem/rust-cache@v2

      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-binstall

      - name: Install dioxus-cli
        run: cargo binstall dioxus-cli

      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v2
        with:
          version: "18.1.8"

      - uses: lukka/get-cmake@latest

      - name: Setup vcpkg and install dependencies
        uses: lukka/run-vcpkg@v11
        with:
          runVcpkgInstall: true
          doNotCache: false

      # - name: Build
      #   shell: bash
      #   run: |
      #     export OPENCV_DIR=$VCPKG_ROOT/installed/$VCPKG_DEFAULT_TRIPLET/share/opencv4
      #     dx build --release --package ui
