name: Build windows-x64-static-release

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  VCPKG_ENABLE_METRICS: 0
  VCPKG_INSTALLED_DIR: ${{ github.workspace }}/vcpkg/installed
  VCPKG_DEFAULT_TRIPLET: x64-windows-static-release
  VCPKG_DEFAULT_HOST_TRIPLET: x64-windows-static-release
  VCPKGRS_TRIPLET: x64-windows-static-release
  CARGO_TERM_COLOR: always
  OPENCV_MSVC_CRT: static
  OPENCV_DISABLE_PROBES: environment,pkg_config,cmake,vcpkg_cmake

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: "npm"
          cache-dependency-path: "./ui/package-lock.json"

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-x86_64-pc-windows-msvc

      - uses: Swatinem/rust-cache@v2

      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-binstall

      - uses: KyleMayes/install-llvm-action@v2
        with:
          version: "18.1.8"

      - uses: lukka/get-cmake@latest
        with:
          cmakeVersion: 3.31.6

      - uses: lukka/run-vcpkg@v11
        with:
          runVcpkgInstall: true

      - name: Build & test
        shell: pwsh
        run: |
          cd ui
          npm install
          cd ../
          cargo binstall dioxus-cli --force
          dx build --verbose --release --package ui
          cargo test --verbose

      - uses: actions/upload-artifact@v4
        with:
          name: app
          path: target/dx/ui/release/windows/app
