name: Build windows-x64-static-release

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  VCPKG_DEFAULT_TRIPLET: x64-windows-static-release
  VCPKG_DEFAULT_HOST_TRIPLET: x64-windows-static-release
  VCPKG_ENABLE_METRICS: 0
  CARGO_TERM_COLOR: always
  OPENCV_MSVC_CRT: static
  OPENCV_DISABLE_PROBES: environment,pkg_config,cmake,vcpkg_cmake

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install toolchain
        run: |
          rustup toolchain install nightly-x86_64-pc-windows-msvc --profile minimal
          rustup default nightly-x86_64-pc-windows-msvc

      - uses: Swatinem/rust-cache@v2

      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-binstall

      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v2
        with:
          version: "18.1.8"

      - uses: lukka/get-cmake@latest

      - name: Setup vcpkg and install dependencies
        uses: lukka/run-vcpkg@v11
        with:
          runVcpkgInstall: true
          doNotCache: false

      - name: Build
        shell: pwsh
        run: |
          cargo binstall dioxus-cli --no-confirm
          cargo build --release

# dx build --verbose --release --package ui
